export const userList = [
  {
    id: 1,
    name: "John Doe",
    username: "johndoe1",
    age: 28,
    nationality: "American",
  },
  {
    id: 2,
    name: "Emma Smith",
    username: "emmasmith2",
    age: 24,
    nationality: "British",
  },
  {
    id: 3,
    name: "Luis Garcia",
    username: "luisgarcia3",
    age: 32,
    nationality: "Mexican",
  },
  {
    id: 4,
    name: "Maria Rossi",
    username: "mariarossi4",
    age: 26,
    nationality: "Italian",
  },
  {
    id: 5,
    name: "Chen Wei",
    username: "chenwei5",
    age: 30,
    nationality: "Chinese",
  },
  {
    id: 6,
    name: "Fatima Ali",
    username: "fatimaali6",
    nationality: "Pakistani",
  },
  {
    id: 7,
    name: "Oliver Brown",
    username: "oliverbrown7",
    age: 27,
    nationality: "Canadian",
  },
  {
    id: 8,
    name: "Sofia Hernández",
    username: "sofiahernandez8",
    age: 25,
    nationality: "Spanish",
  },
  {
    id: 9,
    name: "Nikita Petrov",
    username: "nikitapetrov9",
    age: 33,
    nationality: "Russian",
  },
  {
    id: 10,
    name: "Ayesha Khan",
    username: "ayeshakhan10",
    age: 29,
    nationality: "Indian",
  },
  {
    id: 11,
    name: "Carlos Sanchez",
    username: "carlossanchez11",
    age: 31,
    nationality: "Argentinian",
  },
  {
    id: 12,
    name: "Emily Davis",
    username: "emilydavis12",
    age: 23,
    nationality: "Australian",
  },
  {
    id: 13,
    name: "Yuki Nakamura",
    username: "yukinakamura13",
    age: 28,
    nationality: "Japanese",
  },
  {
    id: 14,
    name: "Ahmed Hassan",
    username: "ahmedhassan14",
    age: 35,
    nationality: "Egyptian",
  },
  {
    id: 15,
    name: "Grace Lee",
    username: "gracelee15",
    age: 26,
    nationality: "South Korean",
  },
  {
    id: 16,
    name: "Jorge Martinez",
    username: "jorgemartinez16",
    age: 34,
    nationality: "Brazilian",
  },
  {
    id: 17,
    name: "Hannah Müller",
    username: "hannahmuller17",
    age: 27,
    nationality: "German",
  },
  {
    id: 18,
    name: "Leila Bennani",
    username: "leilabennani18",
    age: 25,
    nationality: "Moroccan",
  },
  {
    id: 19,
    name: "David Johnson",
    username: "davidjohnson19",
    age: 29,
    nationality: "American",
  },
  {
    id: 20,
    name: "Isabella Silva",
    username: "isabellasilva20",
    age: 24,
    nationality: "Portuguese",
  },
];
