export const userList = [
  {
    id: 1,
    name: "John Doe",
    username: "johndoe1",
    age: 28,
    nationality: "American".toUpperCase(),
    friends: [
      {
        id: 1,
        name: "Nazil",
        username: "nazil1712",
        nationality: "Indian".toUpperCase(),
      },
      {
        id: 2,
        name: "Musharraf",
        username: "mussu1899",
        nationality: "Indian".toUpperCase(),
      },
    ],
  },
  {
    id: 2,
    name: "Emma Smith",
    username: "emmasmith2",
    age: 24,
    nationality: "British".toUpperCase(),
  },
  {
    id: 3,
    name: "Luis Garcia",
    username: "luisgarcia3",
    age: 32,
    nationality: "Mexican".toUpperCase(),
  },
  {
    id: 4,
    name: "Maria Rossi",
    username: "mariarossi4",
    age: 26,
    nationality: "Italian".toUpperCase(),
  },
  {
    id: 5,
    name: "Chen Wei",
    username: "chenwei5",
    age: 30,
    nationality: "Chinese".toUpperCase(),
  },
  {
    id: 6,
    name: "Fatima Ali",
    username: "fatimaali6",
    nationality: "Pakistani".toUpperCase(),
  },
  {
    id: 7,
    name: "Oliver Brown",
    username: "oliverbrown7",
    age: 27,
    nationality: "Canadian".toUpperCase(),
  },
  {
    id: 8,
    name: "Sofia Hernández",
    username: "sofiahernandez8",
    age: 25,
    nationality: "Spanish".toUpperCase(),
  },
  {
    id: 9,
    name: "Nikita Petrov",
    username: "nikitapetrov9",
    age: 33,
    nationality: "Russian".toUpperCase(),
  },
  {
    id: 10,
    name: "Ayesha Khan",
    username: "ayeshakhan10",
    age: 29,
    nationality: "Indian".toUpperCase(),
  },
  {
    id: 11,
    name: "Carlos Sanchez",
    username: "carlossanchez11",
    age: 31,
    nationality: "Argentinian".toUpperCase(),
  },
  {
    id: 12,
    name: "Emily Davis",
    username: "emilydavis12",
    age: 23,
    nationality: "Australian".toUpperCase(),
  },
  {
    id: 13,
    name: "Yuki Nakamura",
    username: "yukinakamura13",
    age: 28,
    nationality: "Japanese".toUpperCase(),
  },
  {
    id: 14,
    name: "Ahmed Hassan",
    username: "ahmedhassan14",
    age: 35,
    nationality: "Egyptian".toUpperCase(),
  },
  {
    id: 15,
    name: "Grace Lee",
    username: "gracelee15",
    age: 26,
    nationality: "Indian".toUpperCase(),
  },
  {
    id: 16,
    name: "Jorge Martinez",
    username: "jorgemartinez16",
    age: 34,
    nationality: "Brazilian".toUpperCase(),
  },
  {
    id: 17,
    name: "Hannah Müller",
    username: "hannahmuller17",
    age: 27,
    nationality: "German".toUpperCase(),
  },
  {
    id: 18,
    name: "Leila Bennani",
    username: "leilabennani18",
    age: 25,
    nationality: "Moroccan".toUpperCase(),
  },
  {
    id: 19,
    name: "David Johnson",
    username: "davidjohnson19",
    age: 29,
    nationality: "American".toUpperCase(),
  },
  {
    id: 20,
    name: "Isabella Silva",
    username: "isabellasilva20",
    age: 24,
    nationality: "Portuguese".toUpperCase(),
  },
];

export const movieList = [
  { id: 1, name: "Inception", yearOfPublication: 2024, isInTheaters: false },
  {
    id: 2,
    name: "The Dark Knight",
    yearOfPublication: 2008,
    isInTheaters: false,
  },
  { id: 3, name: "Interstellar", yearOfPublication: 2014, isInTheaters: false },
  {
    id: 4,
    name: "The Matrix Resurrections",
    yearOfPublication: 2021,
    isInTheaters: false,
  },
  { id: 5, name: "Dune", yearOfPublication: 2021, isInTheaters: true },
  {
    id: 6,
    name: "Avengers: Endgame",
    yearOfPublication: 2019,
    isInTheaters: true,
  },
  {
    id: 7,
    name: "Spider-Man: No Way Home",
    yearOfPublication: 2021,
    isInTheaters: true,
  },
  { id: 8, name: "The Batman", yearOfPublication: 2022, isInTheaters: false },
  {
    id: 9,
    name: "Doctor Strange in the Multiverse of Madness",
    yearOfPublication: 2022,
    isInTheaters: true,
  },
  {
    id: 10,
    name: "Black Panther: Wakanda Forever",
    yearOfPublication: 2022,
    isInTheaters: true,
  },
  { id: 11, name: "Avatar", yearOfPublication: 2009, isInTheaters: true },
  { id: 12, name: "Titanic", yearOfPublication: 1997, isInTheaters: true },
  {
    id: 13,
    name: "Jurassic World Dominion",
    yearOfPublication: 2022,
    isInTheaters: true,
  },
  {
    id: 14,
    name: "Top Gun: Maverick",
    yearOfPublication: 2022,
    isInTheaters: true,
  },
  {
    id: 15,
    name: "Guardians of the Galaxy Vol. 3",
    yearOfPublication: 2023,
    isInTheaters: true,
  },
  {
    id: 16,
    name: "Shang-Chi and the Legend of the Ten Rings",
    yearOfPublication: 2021,
    isInTheaters: false,
  },
  {
    id: 17,
    name: "No Time to Die",
    yearOfPublication: 2021,
    isInTheaters: false,
  },
  {
    id: 18,
    name: "The Suicide Squad",
    yearOfPublication: 2021,
    isInTheaters: false,
  },
  { id: 19, name: "The Lion King", yearOfPublication: 2019, isInTheaters: true },
  { id: 20, name: "Frozen II", yearOfPublication: 2019, isInTheaters: false },
];
